services:
  salt-master:
    image: salt-master:latest
    hostname: salt-master
    volumes:
      - ~/volumes/salt-master/pki:/etc/salt/pki
    ports:
      - 0.0.0.0:4505:4505
      - 0.0.0.0:4506:4506
